/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfface;

import enums.ConsertoLoc;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author angel
 */



public class FMenu extends javax.swing.JFrame {
    
    public FMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPCorpo = new javax.swing.JPanel();
        jPBarMenu = new javax.swing.JPanel();
        jLOpc2 = new javax.swing.JLabel();
        jLTextA = new javax.swing.JLabel();
        jLOpc1 = new javax.swing.JLabel();
        jPLinha = new javax.swing.JPanel();
        jPMenu = new javax.swing.JPanel();
        jPFechar = new javax.swing.JPanel();
        jBFechar = new javax.swing.JButton();
        jPBtnMenu = new javax.swing.JPanel();
        jBMenu1 = new javax.swing.JButton();
        jLTitulo = new javax.swing.JLabel();
        jLTitulo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPCorpo.setBackground(new java.awt.Color(221, 221, 221));
        jPCorpo.setBorder(null);

        jPBarMenu.setBackground(new java.awt.Color(235, 116, 116));
        jPBarMenu.setMaximumSize(new java.awt.Dimension(135, 369));
        jPBarMenu.setMinimumSize(new java.awt.Dimension(0, 369));
        jPBarMenu.setPreferredSize(new java.awt.Dimension(135, 369));

        jLOpc2.setBackground(new java.awt.Color(235, 116, 116));
        jLOpc2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLOpc2.setForeground(new java.awt.Color(255, 255, 255));
        jLOpc2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLOpc2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/tax (1).png"))); // NOI18N
        jLOpc2.setText("Taxa de Armazenagem");
        jLOpc2.setToolTipText("Adicionar taxa de Armazenagem");
        jLOpc2.setBorder(null);
        jLOpc2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLOpc2.setMaximumSize(new java.awt.Dimension(135, 38));
        jLOpc2.setMinimumSize(new java.awt.Dimension(0, 38));
        jLOpc2.setOpaque(true);
        jLOpc2.setPreferredSize(new java.awt.Dimension(135, 38));
        jLOpc2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLOpc2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLOpc2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLOpc2MouseExited(evt);
            }
        });

        jLTextA.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLTextA.setForeground(new java.awt.Color(241, 241, 241));
        jLTextA.setText("By Angelo");

        jLOpc1.setBackground(new java.awt.Color(235, 116, 116));
        jLOpc1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLOpc1.setForeground(new java.awt.Color(255, 255, 255));
        jLOpc1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLOpc1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/car.png"))); // NOI18N
        jLOpc1.setText("Adicionar Veículo");
        jLOpc1.setToolTipText("Adicionar veículo na loja");
        jLOpc1.setBorder(null);
        jLOpc1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLOpc1.setMaximumSize(new java.awt.Dimension(135, 38));
        jLOpc1.setMinimumSize(new java.awt.Dimension(0, 38));
        jLOpc1.setOpaque(true);
        jLOpc1.setPreferredSize(new java.awt.Dimension(135, 38));
        jLOpc1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLOpc1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLOpc1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLOpc1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPBarMenuLayout = new javax.swing.GroupLayout(jPBarMenu);
        jPBarMenu.setLayout(jPBarMenuLayout);
        jPBarMenuLayout.setHorizontalGroup(
            jPBarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLOpc2, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
            .addComponent(jLOpc1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
            .addGroup(jPBarMenuLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLTextA)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPBarMenuLayout.setVerticalGroup(
            jPBarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBarMenuLayout.createSequentialGroup()
                .addComponent(jLOpc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLOpc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 274, Short.MAX_VALUE)
                .addComponent(jLTextA)
                .addContainerGap())
        );

        jPLinha.setBackground(new java.awt.Color(235, 116, 116));
        jPLinha.setBorder(null);
        jPLinha.setPreferredSize(new java.awt.Dimension(578, 1));

        javax.swing.GroupLayout jPLinhaLayout = new javax.swing.GroupLayout(jPLinha);
        jPLinha.setLayout(jPLinhaLayout);
        jPLinhaLayout.setHorizontalGroup(
            jPLinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 643, Short.MAX_VALUE)
        );
        jPLinhaLayout.setVerticalGroup(
            jPLinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPCorpoLayout = new javax.swing.GroupLayout(jPCorpo);
        jPCorpo.setLayout(jPCorpoLayout);
        jPCorpoLayout.setHorizontalGroup(
            jPCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCorpoLayout.createSequentialGroup()
                .addComponent(jPBarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(jPLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPCorpoLayout.setVerticalGroup(
            jPCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPBarMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPCorpoLayout.createSequentialGroup()
                .addGap(339, 339, 339)
                .addComponent(jPLinha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPMenu.setBackground(new java.awt.Color(235, 116, 116));
        jPMenu.setBorder(null);

        jPFechar.setBackground(new java.awt.Color(235, 116, 116));
        jPFechar.setBorder(null);
        jPFechar.setPreferredSize(new java.awt.Dimension(40, 42));

        jBFechar.setBackground(new java.awt.Color(235, 116, 116));
        jBFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/close.png"))); // NOI18N
        jBFechar.setToolTipText("Fechar programa");
        jBFechar.setBorder(null);
        jBFechar.setBorderPainted(false);
        jBFechar.setContentAreaFilled(false);
        jBFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBFecharMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBFecharMouseExited(evt);
            }
        });
        jBFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPFecharLayout = new javax.swing.GroupLayout(jPFechar);
        jPFechar.setLayout(jPFecharLayout);
        jPFecharLayout.setHorizontalGroup(
            jPFecharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPFecharLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPFecharLayout.setVerticalGroup(
            jPFecharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFecharLayout.createSequentialGroup()
                .addComponent(jBFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPBtnMenu.setBackground(new java.awt.Color(235, 116, 116));
        jPBtnMenu.setBorder(null);
        jPBtnMenu.setPreferredSize(new java.awt.Dimension(36, 42));

        jBMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/barras-de-menu16.png"))); // NOI18N
        jBMenu1.setContentAreaFilled(false);
        jBMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBMenu1.setMargin(new java.awt.Insets(0, 0, 0, 2));
        jBMenu1.setPreferredSize(new java.awt.Dimension(36, 42));
        jBMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBMenu1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPBtnMenuLayout = new javax.swing.GroupLayout(jPBtnMenu);
        jPBtnMenu.setLayout(jPBtnMenuLayout);
        jPBtnMenuLayout.setHorizontalGroup(
            jPBtnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPBtnMenuLayout.setVerticalGroup(
            jPBtnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLTitulo.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(244, 244, 244));
        jLTitulo.setText(" Agostinho Mecânica ");

        jLTitulo1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLTitulo1.setForeground(new java.awt.Color(244, 244, 244));
        jLTitulo1.setText("Borracharia e Mecânica");

        javax.swing.GroupLayout jPMenuLayout = new javax.swing.GroupLayout(jPMenu);
        jPMenu.setLayout(jPMenuLayout);
        jPMenuLayout.setHorizontalGroup(
            jPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPMenuLayout.createSequentialGroup()
                .addComponent(jPBtnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLTitulo)
                .addGap(1, 1, 1)
                .addComponent(jLTitulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPFechar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPMenuLayout.setVerticalGroup(
            jPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMenuLayout.createSequentialGroup()
                .addGroup(jPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPFechar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPBtnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPMenuLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTitulo)
                    .addComponent(jLTitulo1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPCorpo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPCorpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFecharActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBFecharActionPerformed

    private void jBFecharMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBFecharMouseEntered
        this.jPFechar.setBackground(new Color(230,85,85));
    }//GEN-LAST:event_jBFecharMouseEntered

    private void jBFecharMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBFecharMouseExited
        this.jPFechar.setBackground(new Color(235,116,116)); 
    }//GEN-LAST:event_jBFecharMouseExited

    private void jBMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBMenu1MouseClicked
        if (jPBarMenu.getWidth() == 170) {
            jPBtnMenu.setBackground(new Color(235,116,116));
            Thread th = new Thread(){
                public void run(){
                    try {
                        for (int i = 170; i >= 0; i--) {
                            Thread.sleep(1);
                            jPBarMenu.setSize(i, 369);
                        }
                    } catch (Exception e) {
                    }
                }
            };th.start();
            jPBarMenu.setSize(0, HEIGHT);
            jLOpc1.setSize(0, 38);
            jLOpc2.setSize(0, 38);
        } else if (jPBarMenu.getWidth() == 0) {
            jPBtnMenu.setBackground(new Color(230,85,85));            
            Thread th = new Thread(){
                public void run(){
                    try {
                        for (int i = 0; i <= 170; i++) {
                            Thread.sleep(1);
                            jPBarMenu.setSize(i, 369);
                        }
                    } catch (Exception e) {
                    }
                }
            };th.start();
            jPBarMenu.setSize(170, HEIGHT);
            jLOpc1.setSize(170, 38);
            jLOpc2.setSize(170, 38);
        }        
    }//GEN-LAST:event_jBMenu1MouseClicked

    private void jLOpc1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLOpc1MouseEntered
        jLOpc1.setBackground(new Color(230,85,85));
    }//GEN-LAST:event_jLOpc1MouseEntered

    private void jLOpc1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLOpc1MouseExited
        jLOpc1.setBackground(new Color(235,116,116));
    }//GEN-LAST:event_jLOpc1MouseExited

    private void jLOpc2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLOpc2MouseEntered
        jLOpc2.setBackground(new Color(230,85,85));
    }//GEN-LAST:event_jLOpc2MouseEntered

    private void jLOpc2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLOpc2MouseExited
        jLOpc2.setBackground(new Color(235,116,116));
    }//GEN-LAST:event_jLOpc2MouseExited

    private void jLOpc1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLOpc1MouseClicked
        FecharMenu();
        new JDialogAddVeic(this, true).setVisible(true);        
    }//GEN-LAST:event_jLOpc1MouseClicked

    private void jLOpc2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLOpc2MouseClicked
        FecharMenu();
        new JDialogDeprecia(this, true).setVisible(true);
    }//GEN-LAST:event_jLOpc2MouseClicked
    /**
     * @param args the command line arguments
     */

    public void FecharMenu(){
        jPBtnMenu.setBackground(new Color(235,116,116));
        Thread th = new Thread(){
            public void run(){
                try {
                    for (int i = 135; i >= 0; i--) {
                        Thread.sleep(1);
                        jPBarMenu.setSize(i, 369);
                    }
                } catch (Exception e) {
                }
            }
        };th.start();
        jPBarMenu.setSize(0, HEIGHT);  
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBFechar;
    private javax.swing.JButton jBMenu1;
    private javax.swing.JLabel jLOpc1;
    private javax.swing.JLabel jLOpc2;
    private javax.swing.JLabel jLTextA;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JLabel jLTitulo1;
    private javax.swing.JPanel jPBarMenu;
    private javax.swing.JPanel jPBtnMenu;
    private javax.swing.JPanel jPCorpo;
    private javax.swing.JPanel jPFechar;
    private javax.swing.JPanel jPLinha;
    private javax.swing.JPanel jPMenu;
    // End of variables declaration//GEN-END:variables
}
