/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfface;

import abstrata.Dados;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author angel
 */
public class JDialogDeprecia extends javax.swing.JDialog {

    /**
     * Creates new form JDialogHotel
     */
    public JDialogDeprecia(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPCabecalho = new javax.swing.JPanel();
        jPReturn = new javax.swing.JPanel();
        jBReturn = new javax.swing.JButton();
        jPBack = new javax.swing.JPanel();
        jBBack = new javax.swing.JButton();
        jPNext = new javax.swing.JPanel();
        jBNext = new javax.swing.JButton();
        jPCentro = new javax.swing.JPanel();
        jPLinha = new javax.swing.JPanel();
        jPTamanho = new javax.swing.JPanel();
        jTFTamanho = new javax.swing.JTextField();
        jLTamanhoText = new javax.swing.JLabel();
        jLAtribuido = new javax.swing.JLabel();
        jPBtn = new javax.swing.JPanel();
        jBAtribuir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPCabecalho.setBackground(new java.awt.Color(235, 116, 116));
        jPCabecalho.setPreferredSize(new java.awt.Dimension(584, 42));

        jPReturn.setBackground(new java.awt.Color(235, 116, 116));
        jPReturn.setPreferredSize(new java.awt.Dimension(40, 42));

        jBReturn.setBackground(new java.awt.Color(235, 116, 116));
        jBReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/return.png"))); // NOI18N
        jBReturn.setToolTipText("Fechar guia atual");
        jBReturn.setBorder(null);
        jBReturn.setBorderPainted(false);
        jBReturn.setContentAreaFilled(false);
        jBReturn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBReturnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBReturnMouseExited(evt);
            }
        });
        jBReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPReturnLayout = new javax.swing.GroupLayout(jPReturn);
        jPReturn.setLayout(jPReturnLayout);
        jPReturnLayout.setHorizontalGroup(
            jPReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPReturnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPReturnLayout.setVerticalGroup(
            jPReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPReturnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPBack.setBackground(new java.awt.Color(235, 116, 116));
        jPBack.setPreferredSize(new java.awt.Dimension(30, 42));

        jBBack.setBackground(new java.awt.Color(235, 116, 116));
        jBBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/back.png"))); // NOI18N
        jBBack.setToolTipText("Clique para voltar(Adicionar Veículo)");
        jBBack.setBorder(null);
        jBBack.setBorderPainted(false);
        jBBack.setContentAreaFilled(false);
        jBBack.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBBack.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBBackMouseExited(evt);
            }
        });
        jBBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPBackLayout = new javax.swing.GroupLayout(jPBack);
        jPBack.setLayout(jPBackLayout);
        jPBackLayout.setHorizontalGroup(
            jPBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPBackLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBBack, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPBackLayout.setVerticalGroup(
            jPBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPBackLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBBack, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPNext.setBackground(new java.awt.Color(235, 116, 116));
        jPNext.setPreferredSize(new java.awt.Dimension(30, 42));

        jBNext.setBackground(new java.awt.Color(235, 116, 116));
        jBNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/next.png"))); // NOI18N
        jBNext.setToolTipText("Clique para avançar(Adicionar Veículo)");
        jBNext.setBorder(null);
        jBNext.setBorderPainted(false);
        jBNext.setContentAreaFilled(false);
        jBNext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBNext.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBNextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBNextMouseExited(evt);
            }
        });
        jBNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPNextLayout = new javax.swing.GroupLayout(jPNext);
        jPNext.setLayout(jPNextLayout);
        jPNextLayout.setHorizontalGroup(
            jPNextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNextLayout.createSequentialGroup()
                .addComponent(jBNext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPNextLayout.setVerticalGroup(
            jPNextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNextLayout.createSequentialGroup()
                .addComponent(jBNext, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jBNext.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout jPCabecalhoLayout = new javax.swing.GroupLayout(jPCabecalho);
        jPCabecalho.setLayout(jPCabecalhoLayout);
        jPCabecalhoLayout.setHorizontalGroup(
            jPCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCabecalhoLayout.createSequentialGroup()
                .addComponent(jPBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPReturn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPCabecalhoLayout.setVerticalGroup(
            jPCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCabecalhoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPReturn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPBack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPNext, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPCentro.setBackground(new java.awt.Color(221, 221, 221));
        jPCentro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(235, 116, 116)));
        jPCentro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPLinha.setBackground(new java.awt.Color(235, 116, 116));

        javax.swing.GroupLayout jPLinhaLayout = new javax.swing.GroupLayout(jPLinha);
        jPLinha.setLayout(jPLinhaLayout);
        jPLinhaLayout.setHorizontalGroup(
            jPLinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPLinhaLayout.setVerticalGroup(
            jPLinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPTamanho.setBackground(new java.awt.Color(221, 221, 221));
        jPTamanho.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPTamanho.setPreferredSize(new java.awt.Dimension(200, 38));

        jTFTamanho.setBackground(new java.awt.Color(221, 221, 221));
        jTFTamanho.setBorder(null);
        jTFTamanho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFTamanhoMouseClicked(evt);
            }
        });
        jTFTamanho.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFTamanhoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPTamanhoLayout = new javax.swing.GroupLayout(jPTamanho);
        jPTamanho.setLayout(jPTamanhoLayout);
        jPTamanhoLayout.setHorizontalGroup(
            jPTamanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTamanhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTFTamanho, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPTamanhoLayout.setVerticalGroup(
            jPTamanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTamanhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTFTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLTamanhoText.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLTamanhoText.setForeground(new java.awt.Color(90, 90, 90));
        jLTamanhoText.setText("Taxa de Depreciação         (em %)");

        jPBtn.setBackground(new java.awt.Color(235, 116, 116));
        jPBtn.setPreferredSize(new java.awt.Dimension(80, 21));

        jBAtribuir.setBackground(new java.awt.Color(235, 116, 116));
        jBAtribuir.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jBAtribuir.setForeground(new java.awt.Color(242, 242, 242));
        jBAtribuir.setText("Atribuir");
        jBAtribuir.setToolTipText("Definir taxa de depreciação");
        jBAtribuir.setBorder(null);
        jBAtribuir.setContentAreaFilled(false);
        jBAtribuir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBAtribuir.setPreferredSize(new java.awt.Dimension(80, 21));
        jBAtribuir.setSelected(true);
        jBAtribuir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBAtribuirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBAtribuirMouseExited(evt);
            }
        });
        jBAtribuir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtribuirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPBtnLayout = new javax.swing.GroupLayout(jPBtn);
        jPBtn.setLayout(jPBtnLayout);
        jPBtnLayout.setHorizontalGroup(
            jPBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBtnLayout.createSequentialGroup()
                .addComponent(jBAtribuir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPBtnLayout.setVerticalGroup(
            jPBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBAtribuir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPCentroLayout = new javax.swing.GroupLayout(jPCentro);
        jPCentro.setLayout(jPCentroLayout);
        jPCentroLayout.setHorizontalGroup(
            jPCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPLinha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPCentroLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLTamanhoText)
                    .addComponent(jPTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPCentroLayout.createSequentialGroup()
                        .addComponent(jPBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLAtribuido)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPCentroLayout.setVerticalGroup(
            jPCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCentroLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLTamanhoText)
                .addGap(1, 1, 1)
                .addComponent(jPTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCentroLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jPBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPCentroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLAtribuido)))
                .addGap(32, 48, Short.MAX_VALUE)
                .addComponent(jPLinha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPCabecalho, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
            .addComponent(jPCentro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPCabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPCentro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBReturnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBReturnMouseEntered
        this.jPReturn.setBackground(new Color(230,85,85));
    }//GEN-LAST:event_jBReturnMouseEntered

    private void jBReturnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBReturnMouseExited
        this.jPReturn.setBackground(new Color(235,116,116));
    }//GEN-LAST:event_jBReturnMouseExited

    private void jBReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBReturnActionPerformed
        dispose();
    }//GEN-LAST:event_jBReturnActionPerformed

    private void jBNextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBNextMouseExited
        jPNext.setBackground(new Color(235,116,116));
    }//GEN-LAST:event_jBNextMouseExited

    private void jBNextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBNextMouseEntered
        jPNext.setBackground(new Color(230,85,85));  
    }//GEN-LAST:event_jBNextMouseEntered

    private void jBNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNextActionPerformed
        dispose();
        new JDialogAddVeic(null, true).setVisible(true);
    }//GEN-LAST:event_jBNextActionPerformed

    private void jBAtribuirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtribuirActionPerformed
        Atribuir();
    }//GEN-LAST:event_jBAtribuirActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        jTFTamanho.setText(Dados.getTaxaDeprec()+"");
    }//GEN-LAST:event_formWindowActivated

    private void jTFTamanhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFTamanhoMouseClicked
        jTFTamanho.setText("");
    }//GEN-LAST:event_jTFTamanhoMouseClicked

    private void jBAtribuirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBAtribuirMouseEntered
        jPBtn.setBackground(new Color(230,85,85));
    }//GEN-LAST:event_jBAtribuirMouseEntered

    private void jBAtribuirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBAtribuirMouseExited
        jPBtn.setBackground(new Color(235,116,116));
    }//GEN-LAST:event_jBAtribuirMouseExited

    private void jTFTamanhoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFTamanhoKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            Atribuir();
        }
    }//GEN-LAST:event_jTFTamanhoKeyPressed

    private void jBBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBackActionPerformed
        dispose();
        new JDialogAddVeic(null, true).setVisible(true);  
    }//GEN-LAST:event_jBBackActionPerformed

    private void jBBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBBackMouseEntered
        jPBack.setBackground(new Color(230,85,85));
    }//GEN-LAST:event_jBBackMouseEntered

    private void jBBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBBackMouseExited
        jPBack.setBackground(new Color(235,116,116));
    }//GEN-LAST:event_jBBackMouseExited

    /**
     * @param args the command line arguments
     */

    public void Atribuir(){
        double TaxaDeprec = 0;
        try{
            TaxaDeprec = Double.parseDouble(jTFTamanho.getText());
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "Valor Incorreto", "Aviso", JOptionPane.ERROR_MESSAGE);
            jTFTamanho.requestFocus();
            return;
        }
        Dados.setTaxaDeprec(TaxaDeprec);
        jTFTamanho.setText("");
        jLAtribuido.setText("Depreciação atribuída com sucesso"); 
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogDeprecia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogDeprecia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogDeprecia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogDeprecia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogDeprecia dialog = new JDialogDeprecia(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAtribuir;
    private javax.swing.JButton jBBack;
    private javax.swing.JButton jBNext;
    private javax.swing.JButton jBReturn;
    private javax.swing.JLabel jLAtribuido;
    private javax.swing.JLabel jLTamanhoText;
    private javax.swing.JPanel jPBack;
    private javax.swing.JPanel jPBtn;
    private javax.swing.JPanel jPCabecalho;
    private javax.swing.JPanel jPCentro;
    private javax.swing.JPanel jPLinha;
    private javax.swing.JPanel jPNext;
    private javax.swing.JPanel jPReturn;
    private javax.swing.JPanel jPTamanho;
    private javax.swing.JTextField jTFTamanho;
    // End of variables declaration//GEN-END:variables
}
