/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfface;

import classes.VeicAdd;
import abstrata.Dados;
import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author angel
 */
public class JDialogAddVeic extends javax.swing.JDialog {

    /**
     * Creates new form JDialogAddVeic
     */
    public JDialogAddVeic(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPMenu = new javax.swing.JPanel();
        jPReturn = new javax.swing.JPanel();
        jBReturn = new javax.swing.JButton();
        jPBack = new javax.swing.JPanel();
        jBBack = new javax.swing.JButton();
        jPNext = new javax.swing.JPanel();
        jBNext = new javax.swing.JButton();
        jTPCentral = new javax.swing.JTabbedPane();
        jPVeiculo = new javax.swing.JPanel();
        jPBtn = new javax.swing.JPanel();
        jBAtribuir = new javax.swing.JButton();
        jLMarcaText = new javax.swing.JLabel();
        jPMarca = new javax.swing.JPanel();
        jTFMarca = new javax.swing.JTextField();
        jLModeloText = new javax.swing.JLabel();
        jPModelo = new javax.swing.JPanel();
        jTFModelo = new javax.swing.JTextField();
        jLAnoFabricacaoText = new javax.swing.JLabel();
        jPAnoFabric = new javax.swing.JPanel();
        jTFAnoFabric = new javax.swing.JTextField();
        jLQuilomeText = new javax.swing.JLabel();
        jPQuilometra = new javax.swing.JPanel();
        jTFQuilometra = new javax.swing.JTextField();
        jLPlacaText = new javax.swing.JLabel();
        jPPlaca = new javax.swing.JPanel();
        jFTFPlaca = new javax.swing.JFormattedTextField();
        jLPrecoText = new javax.swing.JLabel();
        jPPreco = new javax.swing.JPanel();
        jTFPreco = new javax.swing.JTextField();
        jLCombustText = new javax.swing.JLabel();
        jPCombust = new javax.swing.JPanel();
        jTFCombust = new javax.swing.JTextField();
        jBCbMenu = new javax.swing.JButton();
        jPCbBox = new javax.swing.JPanel();
        jLOpcCombo1 = new javax.swing.JLabel();
        jPLCombo1 = new javax.swing.JPanel();
        jLOpcCombo2 = new javax.swing.JLabel();
        jPLCombo2 = new javax.swing.JPanel();
        jLOpcCombo3 = new javax.swing.JLabel();
        jPLCombo3 = new javax.swing.JPanel();
        jLOpcCombo4 = new javax.swing.JLabel();
        jPRegistro = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTRegistro = new javax.swing.JTable();
        jPMenuPanel = new javax.swing.JPanel();
        jPTab1 = new javax.swing.JPanel();
        jBtnTab1 = new javax.swing.JButton();
        jPTab2 = new javax.swing.JPanel();
        jBtnTab2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPMenu.setBackground(new java.awt.Color(235, 116, 116));

        jPReturn.setBackground(new java.awt.Color(235, 116, 116));
        jPReturn.setPreferredSize(new java.awt.Dimension(40, 42));

        jBReturn.setBackground(new java.awt.Color(235, 116, 116));
        jBReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/return.png"))); // NOI18N
        jBReturn.setToolTipText("Fechar guia atual");
        jBReturn.setBorder(null);
        jBReturn.setBorderPainted(false);
        jBReturn.setContentAreaFilled(false);
        jBReturn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBReturnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBReturnMouseExited(evt);
            }
        });
        jBReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPReturnLayout = new javax.swing.GroupLayout(jPReturn);
        jPReturn.setLayout(jPReturnLayout);
        jPReturnLayout.setHorizontalGroup(
            jPReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPReturnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPReturnLayout.setVerticalGroup(
            jPReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPReturnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPBack.setBackground(new java.awt.Color(235, 116, 116));
        jPBack.setPreferredSize(new java.awt.Dimension(30, 42));

        jBBack.setBackground(new java.awt.Color(235, 116, 116));
        jBBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/back.png"))); // NOI18N
        jBBack.setToolTipText("Clique para voltar(Registro Veículos)");
        jBBack.setBorder(null);
        jBBack.setBorderPainted(false);
        jBBack.setContentAreaFilled(false);
        jBBack.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBBack.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBBackMouseExited(evt);
            }
        });
        jBBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPBackLayout = new javax.swing.GroupLayout(jPBack);
        jPBack.setLayout(jPBackLayout);
        jPBackLayout.setHorizontalGroup(
            jPBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPBackLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBBack, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPBackLayout.setVerticalGroup(
            jPBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPBackLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBBack, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPNext.setBackground(new java.awt.Color(235, 116, 116));
        jPNext.setPreferredSize(new java.awt.Dimension(30, 42));

        jBNext.setBackground(new java.awt.Color(235, 116, 116));
        jBNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/next.png"))); // NOI18N
        jBNext.setToolTipText("Clique para avançar(Registro Veículos)");
        jBNext.setBorder(null);
        jBNext.setBorderPainted(false);
        jBNext.setContentAreaFilled(false);
        jBNext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBNext.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBNextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBNextMouseExited(evt);
            }
        });
        jBNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPNextLayout = new javax.swing.GroupLayout(jPNext);
        jPNext.setLayout(jPNextLayout);
        jPNextLayout.setHorizontalGroup(
            jPNextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNextLayout.createSequentialGroup()
                .addComponent(jBNext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPNextLayout.setVerticalGroup(
            jPNextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNextLayout.createSequentialGroup()
                .addComponent(jBNext, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPMenuLayout = new javax.swing.GroupLayout(jPMenu);
        jPMenu.setLayout(jPMenuLayout);
        jPMenuLayout.setHorizontalGroup(
            jPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPMenuLayout.createSequentialGroup()
                .addComponent(jPBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 633, Short.MAX_VALUE)
                .addComponent(jPReturn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPMenuLayout.setVerticalGroup(
            jPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMenuLayout.createSequentialGroup()
                .addGroup(jPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPReturn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPBack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPNext, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPVeiculo.setBackground(new java.awt.Color(221, 221, 221));
        jPVeiculo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(235, 116, 116)));
        jPVeiculo.setMaximumSize(new java.awt.Dimension(584, 401));
        jPVeiculo.setMinimumSize(new java.awt.Dimension(584, 401));

        jPBtn.setBackground(new java.awt.Color(235, 116, 116));
        jPBtn.setPreferredSize(new java.awt.Dimension(80, 21));

        jBAtribuir.setBackground(new java.awt.Color(235, 116, 116));
        jBAtribuir.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jBAtribuir.setForeground(new java.awt.Color(242, 242, 242));
        jBAtribuir.setText("Adicionar");
        jBAtribuir.setToolTipText("Adicionar ao registro");
        jBAtribuir.setBorder(null);
        jBAtribuir.setContentAreaFilled(false);
        jBAtribuir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBAtribuir.setPreferredSize(new java.awt.Dimension(80, 21));
        jBAtribuir.setSelected(true);
        jBAtribuir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBAtribuirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBAtribuirMouseExited(evt);
            }
        });
        jBAtribuir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtribuirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPBtnLayout = new javax.swing.GroupLayout(jPBtn);
        jPBtn.setLayout(jPBtnLayout);
        jPBtnLayout.setHorizontalGroup(
            jPBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBAtribuir, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
        );
        jPBtnLayout.setVerticalGroup(
            jPBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBAtribuir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jLMarcaText.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLMarcaText.setForeground(new java.awt.Color(90, 90, 90));
        jLMarcaText.setText("Marca");

        jPMarca.setBackground(new java.awt.Color(221, 221, 221));
        jPMarca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPMarca.setPreferredSize(new java.awt.Dimension(200, 34));

        jTFMarca.setBackground(new java.awt.Color(221, 221, 221));
        jTFMarca.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTFMarca.setToolTipText(null);
        jTFMarca.setBorder(null);
        jTFMarca.setNextFocusableComponent(jTFAnoFabric);
        jTFMarca.setPreferredSize(new java.awt.Dimension(186, 20));

        javax.swing.GroupLayout jPMarcaLayout = new javax.swing.GroupLayout(jPMarca);
        jPMarca.setLayout(jPMarcaLayout);
        jPMarcaLayout.setHorizontalGroup(
            jPMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMarcaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTFMarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPMarcaLayout.setVerticalGroup(
            jPMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTFMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        jLModeloText.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLModeloText.setForeground(new java.awt.Color(90, 90, 90));
        jLModeloText.setText("Modelo");

        jPModelo.setBackground(new java.awt.Color(221, 221, 221));
        jPModelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPModelo.setPreferredSize(new java.awt.Dimension(200, 34));

        jTFModelo.setBackground(new java.awt.Color(221, 221, 221));
        jTFModelo.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTFModelo.setToolTipText(null);
        jTFModelo.setBorder(null);
        jTFModelo.setNextFocusableComponent(jTFQuilometra);
        jTFModelo.setPreferredSize(new java.awt.Dimension(186, 20));

        javax.swing.GroupLayout jPModeloLayout = new javax.swing.GroupLayout(jPModelo);
        jPModelo.setLayout(jPModeloLayout);
        jPModeloLayout.setHorizontalGroup(
            jPModeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPModeloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTFModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPModeloLayout.setVerticalGroup(
            jPModeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTFModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        jLAnoFabricacaoText.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLAnoFabricacaoText.setForeground(new java.awt.Color(90, 90, 90));
        jLAnoFabricacaoText.setText("Ano de Fabricação");

        jPAnoFabric.setBackground(new java.awt.Color(221, 221, 221));
        jPAnoFabric.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPAnoFabric.setPreferredSize(new java.awt.Dimension(200, 34));

        jTFAnoFabric.setBackground(new java.awt.Color(221, 221, 221));
        jTFAnoFabric.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTFAnoFabric.setToolTipText(null);
        jTFAnoFabric.setBorder(null);
        jTFAnoFabric.setNextFocusableComponent(jTFModelo);
        jTFAnoFabric.setPreferredSize(new java.awt.Dimension(186, 20));

        javax.swing.GroupLayout jPAnoFabricLayout = new javax.swing.GroupLayout(jPAnoFabric);
        jPAnoFabric.setLayout(jPAnoFabricLayout);
        jPAnoFabricLayout.setHorizontalGroup(
            jPAnoFabricLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAnoFabricLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTFAnoFabric, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPAnoFabricLayout.setVerticalGroup(
            jPAnoFabricLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAnoFabricLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTFAnoFabric, javax.swing.GroupLayout.PREFERRED_SIZE, 14, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLQuilomeText.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLQuilomeText.setForeground(new java.awt.Color(90, 90, 90));
        jLQuilomeText.setText("Quilometragem");

        jPQuilometra.setBackground(new java.awt.Color(221, 221, 221));
        jPQuilometra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPQuilometra.setPreferredSize(new java.awt.Dimension(200, 34));

        jTFQuilometra.setBackground(new java.awt.Color(221, 221, 221));
        jTFQuilometra.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTFQuilometra.setToolTipText(null);
        jTFQuilometra.setBorder(null);
        jTFQuilometra.setNextFocusableComponent(jFTFPlaca);
        jTFQuilometra.setPreferredSize(new java.awt.Dimension(186, 20));

        javax.swing.GroupLayout jPQuilometraLayout = new javax.swing.GroupLayout(jPQuilometra);
        jPQuilometra.setLayout(jPQuilometraLayout);
        jPQuilometraLayout.setHorizontalGroup(
            jPQuilometraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPQuilometraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTFQuilometra, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPQuilometraLayout.setVerticalGroup(
            jPQuilometraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPQuilometraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTFQuilometra, javax.swing.GroupLayout.PREFERRED_SIZE, 14, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLPlacaText.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLPlacaText.setForeground(new java.awt.Color(90, 90, 90));
        jLPlacaText.setText("Placa");

        jPPlaca.setBackground(new java.awt.Color(221, 221, 221));
        jPPlaca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPPlaca.setPreferredSize(new java.awt.Dimension(200, 34));

        jFTFPlaca.setBackground(new java.awt.Color(221, 221, 221));
        jFTFPlaca.setBorder(null);
        try {
            jFTFPlaca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UUU-#A##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFPlaca.setToolTipText(null);
        jFTFPlaca.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jFTFPlaca.setNextFocusableComponent(jTFPreco);
        jFTFPlaca.setPreferredSize(new java.awt.Dimension(186, 14));

        javax.swing.GroupLayout jPPlacaLayout = new javax.swing.GroupLayout(jPPlaca);
        jPPlaca.setLayout(jPPlacaLayout);
        jPPlacaLayout.setHorizontalGroup(
            jPPlacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPlacaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFTFPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPPlacaLayout.setVerticalGroup(
            jPPlacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPPlacaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jFTFPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLPrecoText.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLPrecoText.setForeground(new java.awt.Color(90, 90, 90));
        jLPrecoText.setText("Preço(R$)");

        jPPreco.setBackground(new java.awt.Color(221, 221, 221));
        jPPreco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jTFPreco.setBackground(new java.awt.Color(221, 221, 221));
        jTFPreco.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTFPreco.setToolTipText(null);
        jTFPreco.setBorder(null);
        jTFPreco.setMaximumSize(new java.awt.Dimension(2147483647, 14));
        jTFPreco.setMinimumSize(new java.awt.Dimension(1, 14));
        jTFPreco.setNextFocusableComponent(jTFMarca);
        jTFPreco.setPreferredSize(new java.awt.Dimension(186, 14));

        javax.swing.GroupLayout jPPrecoLayout = new javax.swing.GroupLayout(jPPreco);
        jPPreco.setLayout(jPPrecoLayout);
        jPPrecoLayout.setHorizontalGroup(
            jPPrecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPrecoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTFPreco, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPPrecoLayout.setVerticalGroup(
            jPPrecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPrecoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTFPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLCombustText.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLCombustText.setForeground(new java.awt.Color(90, 90, 90));
        jLCombustText.setText("Combustível");

        jPCombust.setBackground(new java.awt.Color(221, 221, 221));
        jPCombust.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPCombust.setPreferredSize(new java.awt.Dimension(200, 34));

        jTFCombust.setEditable(false);
        jTFCombust.setBackground(new java.awt.Color(221, 221, 221));
        jTFCombust.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTFCombust.setText("Gasolina");
        jTFCombust.setToolTipText(null);
        jTFCombust.setBorder(null);
        jTFCombust.setPreferredSize(new java.awt.Dimension(186, 14));

        jBCbMenu.setBackground(new java.awt.Color(235, 116, 116));
        jBCbMenu.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jBCbMenu.setForeground(new java.awt.Color(242, 242, 242));
        jBCbMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/down-arrow.png"))); // NOI18N
        jBCbMenu.setBorder(null);
        jBCbMenu.setContentAreaFilled(false);
        jBCbMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBCbMenu.setSelected(true);
        jBCbMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCbMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPCombustLayout = new javax.swing.GroupLayout(jPCombust);
        jPCombust.setLayout(jPCombustLayout);
        jPCombustLayout.setHorizontalGroup(
            jPCombustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCombustLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTFCombust, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jBCbMenu)
                .addContainerGap())
        );
        jPCombustLayout.setVerticalGroup(
            jPCombustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCombustLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPCombustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFCombust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCbMenu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPCbBox.setBackground(new java.awt.Color(249, 249, 249));
        jPCbBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPCbBox.setMaximumSize(new java.awt.Dimension(165, 117));
        jPCbBox.setMinimumSize(new java.awt.Dimension(165, 0));
        jPCbBox.setPreferredSize(new java.awt.Dimension(165, 117));

        jLOpcCombo1.setBackground(new java.awt.Color(249, 249, 249));
        jLOpcCombo1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLOpcCombo1.setText(" Gasolina");
        jLOpcCombo1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLOpcCombo1.setMaximumSize(new java.awt.Dimension(163, 28));
        jLOpcCombo1.setMinimumSize(new java.awt.Dimension(163, 28));
        jLOpcCombo1.setOpaque(true);
        jLOpcCombo1.setPreferredSize(new java.awt.Dimension(163, 28));
        jLOpcCombo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLOpcCombo1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLOpcCombo1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLOpcCombo1MouseExited(evt);
            }
        });

        jPLCombo1.setBackground(new java.awt.Color(153, 153, 153));
        jPLCombo1.setMaximumSize(new java.awt.Dimension(163, 1));
        jPLCombo1.setMinimumSize(new java.awt.Dimension(163, 1));
        jPLCombo1.setPreferredSize(new java.awt.Dimension(163, 1));

        javax.swing.GroupLayout jPLCombo1Layout = new javax.swing.GroupLayout(jPLCombo1);
        jPLCombo1.setLayout(jPLCombo1Layout);
        jPLCombo1Layout.setHorizontalGroup(
            jPLCombo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 163, Short.MAX_VALUE)
        );
        jPLCombo1Layout.setVerticalGroup(
            jPLCombo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jLOpcCombo2.setBackground(new java.awt.Color(249, 249, 249));
        jLOpcCombo2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLOpcCombo2.setText(" Gás");
        jLOpcCombo2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLOpcCombo2.setMaximumSize(new java.awt.Dimension(163, 28));
        jLOpcCombo2.setMinimumSize(new java.awt.Dimension(163, 28));
        jLOpcCombo2.setOpaque(true);
        jLOpcCombo2.setPreferredSize(new java.awt.Dimension(163, 28));
        jLOpcCombo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLOpcCombo2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLOpcCombo2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLOpcCombo2MouseExited(evt);
            }
        });

        jPLCombo2.setBackground(new java.awt.Color(153, 153, 153));
        jPLCombo2.setMaximumSize(new java.awt.Dimension(163, 1));
        jPLCombo2.setMinimumSize(new java.awt.Dimension(163, 1));
        jPLCombo2.setPreferredSize(new java.awt.Dimension(163, 1));

        javax.swing.GroupLayout jPLCombo2Layout = new javax.swing.GroupLayout(jPLCombo2);
        jPLCombo2.setLayout(jPLCombo2Layout);
        jPLCombo2Layout.setHorizontalGroup(
            jPLCombo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 163, Short.MAX_VALUE)
        );
        jPLCombo2Layout.setVerticalGroup(
            jPLCombo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jLOpcCombo3.setBackground(new java.awt.Color(249, 249, 249));
        jLOpcCombo3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLOpcCombo3.setText(" Etanol");
        jLOpcCombo3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLOpcCombo3.setMaximumSize(new java.awt.Dimension(163, 28));
        jLOpcCombo3.setMinimumSize(new java.awt.Dimension(163, 28));
        jLOpcCombo3.setOpaque(true);
        jLOpcCombo3.setPreferredSize(new java.awt.Dimension(163, 28));
        jLOpcCombo3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLOpcCombo3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLOpcCombo3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLOpcCombo3MouseExited(evt);
            }
        });

        jPLCombo3.setBackground(new java.awt.Color(153, 153, 153));
        jPLCombo3.setMaximumSize(new java.awt.Dimension(163, 1));
        jPLCombo3.setMinimumSize(new java.awt.Dimension(163, 1));
        jPLCombo3.setPreferredSize(new java.awt.Dimension(163, 1));

        javax.swing.GroupLayout jPLCombo3Layout = new javax.swing.GroupLayout(jPLCombo3);
        jPLCombo3.setLayout(jPLCombo3Layout);
        jPLCombo3Layout.setHorizontalGroup(
            jPLCombo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 163, Short.MAX_VALUE)
        );
        jPLCombo3Layout.setVerticalGroup(
            jPLCombo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jLOpcCombo4.setBackground(new java.awt.Color(249, 249, 249));
        jLOpcCombo4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLOpcCombo4.setText(" Diesel");
        jLOpcCombo4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLOpcCombo4.setMaximumSize(new java.awt.Dimension(163, 28));
        jLOpcCombo4.setMinimumSize(new java.awt.Dimension(163, 28));
        jLOpcCombo4.setOpaque(true);
        jLOpcCombo4.setPreferredSize(new java.awt.Dimension(163, 28));
        jLOpcCombo4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLOpcCombo4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLOpcCombo4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLOpcCombo4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPCbBoxLayout = new javax.swing.GroupLayout(jPCbBox);
        jPCbBox.setLayout(jPCbBoxLayout);
        jPCbBoxLayout.setHorizontalGroup(
            jPCbBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLOpcCombo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPCbBoxLayout.createSequentialGroup()
                .addGroup(jPCbBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPLCombo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPLCombo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLOpcCombo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPLCombo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLOpcCombo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLOpcCombo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPCbBoxLayout.setVerticalGroup(
            jPCbBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCbBoxLayout.createSequentialGroup()
                .addComponent(jLOpcCombo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPLCombo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jLOpcCombo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPLCombo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jLOpcCombo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPLCombo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jLOpcCombo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPVeiculoLayout = new javax.swing.GroupLayout(jPVeiculo);
        jPVeiculo.setLayout(jPVeiculoLayout);
        jPVeiculoLayout.setHorizontalGroup(
            jPVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPVeiculoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPVeiculoLayout.createSequentialGroup()
                        .addGroup(jPVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLMarcaText)
                            .addComponent(jPMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(jLModeloText)
                            .addComponent(jPModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(jPVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLQuilomeText)
                            .addGroup(jPVeiculoLayout.createSequentialGroup()
                                .addGroup(jPVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLAnoFabricacaoText)
                                    .addComponent(jPAnoFabric, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPCbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLCombustText)
                                    .addComponent(jPCombust, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPQuilometra, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPVeiculoLayout.createSequentialGroup()
                        .addGroup(jPVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPVeiculoLayout.createSequentialGroup()
                                .addComponent(jLPlacaText)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPPlaca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLPrecoText)
                            .addGroup(jPVeiculoLayout.createSequentialGroup()
                                .addComponent(jPPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(291, Short.MAX_VALUE))))
        );
        jPVeiculoLayout.setVerticalGroup(
            jPVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPVeiculoLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPVeiculoLayout.createSequentialGroup()
                            .addComponent(jLMarcaText)
                            .addGap(1, 1, 1)
                            .addComponent(jPMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPVeiculoLayout.createSequentialGroup()
                            .addComponent(jLAnoFabricacaoText)
                            .addGap(1, 1, 1)
                            .addComponent(jPAnoFabric, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPVeiculoLayout.createSequentialGroup()
                        .addComponent(jLCombustText)
                        .addGap(1, 1, 1)
                        .addComponent(jPCombust, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jPCbBox, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPVeiculoLayout.createSequentialGroup()
                        .addComponent(jLModeloText)
                        .addGap(1, 1, 1)
                        .addComponent(jPModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPVeiculoLayout.createSequentialGroup()
                        .addComponent(jLQuilomeText)
                        .addGap(1, 1, 1)
                        .addComponent(jPQuilometra, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPVeiculoLayout.createSequentialGroup()
                        .addComponent(jLPrecoText)
                        .addGap(1, 1, 1)
                        .addGroup(jPVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPVeiculoLayout.createSequentialGroup()
                        .addComponent(jLPlacaText)
                        .addGap(1, 1, 1)
                        .addComponent(jPPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(158, 158, 158))))
        );

        jTPCentral.addTab("tab1", jPVeiculo);

        jPRegistro.setBackground(new java.awt.Color(235, 116, 116));
        jPRegistro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(235, 116, 116)));

        jScrollPane1.setBackground(new java.awt.Color(242, 242, 242));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(235, 116, 116)));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(300, 200));

        jTRegistro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Modelo", "Placa", "Ano de Fabric.", "Quilometragem", "Combustível", "Preço", "Depreciação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTRegistro.setGridColor(new java.awt.Color(155, 155, 155));
        jTRegistro.setRowHeight(22);
        jTRegistro.setSelectionBackground(new java.awt.Color(235, 116, 116));
        jTRegistro.setShowGrid(true);
        jScrollPane1.setViewportView(jTRegistro);
        if (jTRegistro.getColumnModel().getColumnCount() > 0) {
            jTRegistro.getColumnModel().getColumn(0).setMinWidth(95);
            jTRegistro.getColumnModel().getColumn(0).setPreferredWidth(95);
            jTRegistro.getColumnModel().getColumn(1).setMinWidth(98);
            jTRegistro.getColumnModel().getColumn(1).setPreferredWidth(98);
            jTRegistro.getColumnModel().getColumn(2).setMinWidth(80);
            jTRegistro.getColumnModel().getColumn(2).setPreferredWidth(80);
            jTRegistro.getColumnModel().getColumn(3).setMinWidth(90);
            jTRegistro.getColumnModel().getColumn(3).setPreferredWidth(90);
            jTRegistro.getColumnModel().getColumn(4).setMinWidth(100);
            jTRegistro.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTRegistro.getColumnModel().getColumn(5).setMinWidth(85);
            jTRegistro.getColumnModel().getColumn(5).setPreferredWidth(85);
            jTRegistro.getColumnModel().getColumn(6).setMinWidth(90);
            jTRegistro.getColumnModel().getColumn(6).setPreferredWidth(90);
            jTRegistro.getColumnModel().getColumn(7).setMinWidth(90);
            jTRegistro.getColumnModel().getColumn(7).setPreferredWidth(90);
        }

        javax.swing.GroupLayout jPRegistroLayout = new javax.swing.GroupLayout(jPRegistro);
        jPRegistro.setLayout(jPRegistroLayout);
        jPRegistroLayout.setHorizontalGroup(
            jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRegistroLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPRegistroLayout.setVerticalGroup(
            jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPRegistroLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE))
        );

        jTPCentral.addTab("tab2", jPRegistro);

        jPMenuPanel.setBackground(new java.awt.Color(235, 116, 116));
        jPMenuPanel.setPreferredSize(new java.awt.Dimension(446, 25));

        jPTab1.setBackground(new java.awt.Color(235, 116, 116));
        jPTab1.setPreferredSize(new java.awt.Dimension(100, 15));

        jBtnTab1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jBtnTab1.setForeground(new java.awt.Color(244, 244, 244));
        jBtnTab1.setText("  Veículo");
        jBtnTab1.setBorder(null);
        jBtnTab1.setContentAreaFilled(false);
        jBtnTab1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnTab1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBtnTab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnTab1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnTab1MouseExited(evt);
            }
        });
        jBtnTab1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTab1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPTab1Layout = new javax.swing.GroupLayout(jPTab1);
        jPTab1.setLayout(jPTab1Layout);
        jPTab1Layout.setHorizontalGroup(
            jPTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnTab1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        jPTab1Layout.setVerticalGroup(
            jPTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnTab1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        jPTab2.setBackground(new java.awt.Color(235, 116, 116));
        jPTab2.setToolTipText(null);
        jPTab2.setPreferredSize(new java.awt.Dimension(100, 15));

        jBtnTab2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jBtnTab2.setForeground(new java.awt.Color(244, 244, 244));
        jBtnTab2.setText("  Registro");
        jBtnTab2.setToolTipText(null);
        jBtnTab2.setBorder(null);
        jBtnTab2.setContentAreaFilled(false);
        jBtnTab2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnTab2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBtnTab2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jBtnTab2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnTab2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnTab2MouseExited(evt);
            }
        });
        jBtnTab2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTab2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPTab2Layout = new javax.swing.GroupLayout(jPTab2);
        jPTab2.setLayout(jPTab2Layout);
        jPTab2Layout.setHorizontalGroup(
            jPTab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnTab2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        jPTab2Layout.setVerticalGroup(
            jPTab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnTab2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPMenuPanelLayout = new javax.swing.GroupLayout(jPMenuPanel);
        jPMenuPanel.setLayout(jPMenuPanelLayout);
        jPMenuPanelLayout.setHorizontalGroup(
            jPMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMenuPanelLayout.createSequentialGroup()
                .addComponent(jPTab1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPTab2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(472, Short.MAX_VALUE))
        );
        jPMenuPanelLayout.setVerticalGroup(
            jPMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPTab1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
            .addComponent(jPTab2, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
                    .addComponent(jPMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTPCentral))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 33, Short.MAX_VALUE)
                    .addComponent(jTPCentral, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBReturnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBReturnMouseEntered
        this.jPReturn.setBackground(new Color(230,85,85));
    }//GEN-LAST:event_jBReturnMouseEntered

    private void jBReturnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBReturnMouseExited
        this.jPReturn.setBackground(new Color(235,116,116));
    }//GEN-LAST:event_jBReturnMouseExited

    private void jBReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBReturnActionPerformed
        dispose();
    }//GEN-LAST:event_jBReturnActionPerformed

    private void jBBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBBackMouseEntered
        jPBack.setBackground(new Color(230,85,85));
    }//GEN-LAST:event_jBBackMouseEntered

    private void jBBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBBackMouseExited
        jPBack.setBackground(new Color(235,116,116));
    }//GEN-LAST:event_jBBackMouseExited

    private void jBBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBackActionPerformed
        dispose();
        new JDialogDeprecia(null, true).setVisible(true);
    }//GEN-LAST:event_jBBackActionPerformed

    private void jBNextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBNextMouseEntered
        jPNext.setBackground(new Color(230,85,85));
    }//GEN-LAST:event_jBNextMouseEntered

    private void jBNextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBNextMouseExited
        jPNext.setBackground(new Color(235,116,116));
    }//GEN-LAST:event_jBNextMouseExited

    private void jBNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNextActionPerformed
        dispose();
        new JDialogDeprecia(null, true).setVisible(true);
    }//GEN-LAST:event_jBNextActionPerformed

    private void jBCbMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCbMenuActionPerformed
        MenuCB();
    }//GEN-LAST:event_jBCbMenuActionPerformed

    private void jLOpcCombo1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLOpcCombo1MouseEntered
        jLOpcCombo1.setBackground(new Color(226,226,226));
    }//GEN-LAST:event_jLOpcCombo1MouseEntered

    private void jLOpcCombo1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLOpcCombo1MouseExited
        jLOpcCombo1.setBackground(new Color(249,249,249));
    }//GEN-LAST:event_jLOpcCombo1MouseExited

    private void jLOpcCombo2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLOpcCombo2MouseEntered
        jLOpcCombo2.setBackground(new Color(226,226,226));
    }//GEN-LAST:event_jLOpcCombo2MouseEntered

    private void jLOpcCombo2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLOpcCombo2MouseExited
        jLOpcCombo2.setBackground(new Color(249,249,249));
    }//GEN-LAST:event_jLOpcCombo2MouseExited

    private void jLOpcCombo3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLOpcCombo3MouseEntered
        jLOpcCombo3.setBackground(new Color(226,226,226));
    }//GEN-LAST:event_jLOpcCombo3MouseEntered

    private void jLOpcCombo3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLOpcCombo3MouseExited
        jLOpcCombo3.setBackground(new Color(249,249,249));
    }//GEN-LAST:event_jLOpcCombo3MouseExited

    private void jLOpcCombo4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLOpcCombo4MouseEntered
        jLOpcCombo4.setBackground(new Color(226,226,226));
    }//GEN-LAST:event_jLOpcCombo4MouseEntered

    private void jLOpcCombo4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLOpcCombo4MouseExited
        jLOpcCombo4.setBackground(new Color(249,249,249));
    }//GEN-LAST:event_jLOpcCombo4MouseExited

    private void jBAtribuirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBAtribuirMouseEntered
        jPBtn.setBackground(new Color(230,85,85));
    }//GEN-LAST:event_jBAtribuirMouseEntered

    private void jBAtribuirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBAtribuirMouseExited
        jPBtn.setBackground(new Color(235,116,116));
    }//GEN-LAST:event_jBAtribuirMouseExited

    private void jBAtribuirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtribuirActionPerformed
        if(jTFMarca.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Marca obrigatório!", "Aviso", JOptionPane.ERROR_MESSAGE);
            jTFMarca.requestFocus();
            return;
        }
        if(jTFModelo.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Modelo obrigatório!", "Aviso", JOptionPane.ERROR_MESSAGE);
            jTFModelo.requestFocus();
            return;
        }
        if((jFTFPlaca.getText().trim().isEmpty()) || (jFTFPlaca.getText().length() != 8)){
            JOptionPane.showMessageDialog(null, "Verifique se a placa informada está correta!", "Aviso", JOptionPane.ERROR_MESSAGE);
            jFTFPlaca.requestFocus();
            return;
        }      
                 
        int Ano, Quilo = 0;
        double valor = 0;
        try {
            Ano = Integer.parseInt(jTFAnoFabric.getText());
            Quilo = Integer.parseInt(jTFQuilometra.getText());
            valor = Double.parseDouble(jTFPreco.getText());
            if ((Ano <= 1910) || (Ano >= 2022)){
                JOptionPane.showMessageDialog(null, "Ano de fabricação inválido!", "Aviso", JOptionPane.ERROR_MESSAGE);
                jTFAnoFabric.requestFocus();   
                return;
            }
            if(Quilo < 0){
                JOptionPane.showMessageDialog(null, "Quilometragem inválida(valor negativo)!", "Aviso", JOptionPane.ERROR_MESSAGE);
                jTFQuilometra.requestFocus();   
                return;
            }
            if(valor < 0){
                JOptionPane.showMessageDialog(null, "Preço inválido(valor negativo)!", "Aviso", JOptionPane.ERROR_MESSAGE);
                jTFPreco.requestFocus();     
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Erro numérico, verifique os campos Ano de fabricação, Quilometragem ou Preço!", "Aviso", JOptionPane.ERROR_MESSAGE);
            jTFAnoFabric.requestFocus();
            return;            
        }     
        
        VeicAdd veicadd = new VeicAdd(jTFMarca.getText(), jTFModelo.getText(), jFTFPlaca.getText(), Ano, Quilo, jTFCombust.getText(), valor);
        Dados.getListaVeic().add(veicadd);
        
        jTFMarca.setText("");
        jTFModelo.setText("");
        jFTFPlaca.setText("");
        jTFPreco.setText("");
        jTFQuilometra.setText("");
        jTFAnoFabric.setText("");
        jTFCombust.setText("Gasolina");       
        
        jTFMarca.requestFocus();
    }//GEN-LAST:event_jBAtribuirActionPerformed

    private void jLOpcCombo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLOpcCombo1MouseClicked
        jTFCombust.setText(jLOpcCombo1.getText().trim());
        MenuCB();
    }//GEN-LAST:event_jLOpcCombo1MouseClicked

    private void jLOpcCombo2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLOpcCombo2MouseClicked
        jTFCombust.setText(jLOpcCombo2.getText().trim());  
        MenuCB();
    }//GEN-LAST:event_jLOpcCombo2MouseClicked

    private void jLOpcCombo3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLOpcCombo3MouseClicked
        jTFCombust.setText(jLOpcCombo3.getText().trim());   
        MenuCB();
    }//GEN-LAST:event_jLOpcCombo3MouseClicked

    private void jLOpcCombo4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLOpcCombo4MouseClicked
        jTFCombust.setText(jLOpcCombo4.getText().trim());   
        MenuCB();
    }//GEN-LAST:event_jLOpcCombo4MouseClicked

    private void jBtnTab1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTab1ActionPerformed
        jTPCentral.setSelectedIndex(0);
        jTFMarca.requestFocus();
    }//GEN-LAST:event_jBtnTab1ActionPerformed

    private void jBtnTab2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTab2ActionPerformed
        jTPCentral.setSelectedIndex(1);
        Listar();
    }//GEN-LAST:event_jBtnTab2ActionPerformed

    private void jBtnTab1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTab1MouseExited
        jPTab1.setBackground(new Color(235,116,116));
    }//GEN-LAST:event_jBtnTab1MouseExited

    private void jBtnTab1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTab1MouseEntered
        jPTab1.setBackground(new Color(230,85,85));
    }//GEN-LAST:event_jBtnTab1MouseEntered

    private void jBtnTab2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTab2MouseExited
        jPTab2.setBackground(new Color(235,116,116));
    }//GEN-LAST:event_jBtnTab2MouseExited

    private void jBtnTab2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTab2MouseEntered
        jPTab2.setBackground(new Color(230,85,85));
    }//GEN-LAST:event_jBtnTab2MouseEntered

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jScrollPane1.getViewport().setBackground(new Color(221,221,221));
        jTRegistro.getTableHeader().setFont(new Font("Tahoma", Font.PLAIN, 12));   
        jTFMarca.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    
    public void Listar(){
        DefaultTableModel lista = (DefaultTableModel) jTRegistro.getModel();
        lista.setRowCount(0);
        for(VeicAdd veicadd : Dados.getListaVeic()){
            lista.addRow(new Object[]{
                veicadd.getMarca(),
                veicadd.getModelo(),
                veicadd.getPlaca(),    
                veicadd.getAnoFabricacao(),
                veicadd.getQuilometragem(),
                veicadd.getCombustivel(),
                String.format("R$%.2f", veicadd.getPreco()),
                String.format("R$%.2f", veicadd.getValorDeprec())
            });
        }    
    }
    public void MenuCB(){
        jBCbMenu.setIcon(new ImageIcon(getClass().getResource("/Icons/down-arrow.png")));
        if(jPCbBox.getHeight() == 0){
            jPCbBox.setSize(165, 117);
            jBCbMenu.setIcon(new ImageIcon(getClass().getResource("/Icons/upload.png")));
        }   else{
            jPCbBox.setSize(165, 0);
            jBCbMenu.setIcon(new ImageIcon(getClass().getResource("/Icons/down-arrow.png")));
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogAddVeic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogAddVeic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogAddVeic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogAddVeic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogAddVeic dialog = new JDialogAddVeic(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAtribuir;
    private javax.swing.JButton jBBack;
    private javax.swing.JButton jBCbMenu;
    private javax.swing.JButton jBNext;
    private javax.swing.JButton jBReturn;
    private javax.swing.JButton jBtnTab1;
    private javax.swing.JButton jBtnTab2;
    private javax.swing.JFormattedTextField jFTFPlaca;
    private javax.swing.JLabel jLAnoFabricacaoText;
    private javax.swing.JLabel jLCombustText;
    private javax.swing.JLabel jLMarcaText;
    private javax.swing.JLabel jLModeloText;
    private javax.swing.JLabel jLOpcCombo1;
    private javax.swing.JLabel jLOpcCombo2;
    private javax.swing.JLabel jLOpcCombo3;
    private javax.swing.JLabel jLOpcCombo4;
    private javax.swing.JLabel jLPlacaText;
    private javax.swing.JLabel jLPrecoText;
    private javax.swing.JLabel jLQuilomeText;
    private javax.swing.JPanel jPAnoFabric;
    private javax.swing.JPanel jPBack;
    private javax.swing.JPanel jPBtn;
    private javax.swing.JPanel jPCbBox;
    private javax.swing.JPanel jPCombust;
    private javax.swing.JPanel jPLCombo1;
    private javax.swing.JPanel jPLCombo2;
    private javax.swing.JPanel jPLCombo3;
    private javax.swing.JPanel jPMarca;
    private javax.swing.JPanel jPMenu;
    private javax.swing.JPanel jPMenuPanel;
    private javax.swing.JPanel jPModelo;
    private javax.swing.JPanel jPNext;
    private javax.swing.JPanel jPPlaca;
    private javax.swing.JPanel jPPreco;
    private javax.swing.JPanel jPQuilometra;
    private javax.swing.JPanel jPRegistro;
    private javax.swing.JPanel jPReturn;
    private javax.swing.JPanel jPTab1;
    private javax.swing.JPanel jPTab2;
    private javax.swing.JPanel jPVeiculo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFAnoFabric;
    private javax.swing.JTextField jTFCombust;
    private javax.swing.JTextField jTFMarca;
    private javax.swing.JTextField jTFModelo;
    private javax.swing.JTextField jTFPreco;
    private javax.swing.JTextField jTFQuilometra;
    private javax.swing.JTabbedPane jTPCentral;
    private javax.swing.JTable jTRegistro;
    // End of variables declaration//GEN-END:variables
}
